import { createHash, randomUUID } from 'node:crypto';
import { AppError } from '../core/app-error.js';
import {
  optionalString,
  requireEnum,
  requireInteger,
  requireString,
} from '../core/validation.js';
import { encryptText, generateSigningKeyPair } from '../security/crypto.js';
import {
  assertMerchantAccess,
  assertRole,
  findApplicationOrThrow,
  findMerchantOrThrow,
  Roles,
} from './access-control.js';
import { AuditService } from './audit-service.js';
import {
  assertVersionPolicyConsistent,
  normalizeApplicationBinding,
  normalizeClientRelease,
} from './client-integrity.js';
import { presentApplication } from './presenters.js';

const APP_CODE_PATTERN = /^[A-Z0-9][A-Z0-9_-]{1,31}$/;

function readSettings(input, defaults = {}) {
  return {
    defaultDurationDays: requireInteger(
      input.defaultDurationDays ?? defaults.defaultDurationDays ?? 30,
      'settings.defaultDurationDays',
      { min: 1, max: 3650 },
    ),
    defaultMaxDevices: requireInteger(
      input.defaultMaxDevices ?? defaults.defaultMaxDevices ?? 1,
      'settings.defaultMaxDevices',
      { min: 0, max: 20 },
    ),
    heartbeatSeconds: requireInteger(
      input.heartbeatSeconds ?? defaults.heartbeatSeconds ?? 300,
      'settings.heartbeatSeconds',
      { min: 30, max: 86400 },
    ),
    offlineGraceSeconds: requireInteger(
      input.offlineGraceSeconds ?? defaults.offlineGraceSeconds ?? 900,
      'settings.offlineGraceSeconds',
      { min: 60, max: 604800 },
    ),
  };
}

// 花落 / MIT：绑定约束与版本发布策略的写入逻辑。MySQL 仓储与 JSON 事务两条路径共用，
// 避免两边逻辑漂移。自锁校验必须基于「已有值 + 本次修改」的最终值，否则单独 PATCH
// minVersionCode 时会绕过检查，把全部客户端锁死在没有升级目标的状态。
function applyBindingAndRelease(current, input) {
  const binding = normalizeApplicationBinding(input);
  if (binding.androidPackage !== undefined) current.androidPackage = binding.androidPackage;
  if (binding.signingCertificates !== undefined) current.signingCertificates = binding.signingCertificates;
  if (binding.minVersionCode !== undefined) current.minVersionCode = binding.minVersionCode;
  const release = normalizeClientRelease(input);
  if (release.latestVersionCode !== undefined) current.latestVersionCode = release.latestVersionCode;
  if (release.latestVersionName !== undefined) current.latestVersionName = release.latestVersionName;
  if (release.releaseNotes !== undefined) current.releaseNotes = release.releaseNotes;
  assertVersionPolicyConsistent(current.minVersionCode, current.latestVersionCode);
}

function createClientConfig(application, runtimeConfig) {
  const config = {
    protocolVersion: runtimeConfig.protocolVersion,
    baseUrl: runtimeConfig.publicBaseUrl,
    appId: application.id,
    keyId: application.signingKeyId,
    publicKey: application.signingPublicKey,
  };
  const cppHeader = `#pragma once\n// Generated by KMXT. Author: 花落. MIT License.\nnamespace kmxt::config {\ninline constexpr int protocol_version = ${config.protocolVersion};\ninline constexpr char base_url[] = R"KMXT(${config.baseUrl})KMXT";\ninline constexpr char app_id[] = R"KMXT(${config.appId})KMXT";\ninline constexpr char key_id[] = R"KMXT(${config.keyId})KMXT";\ninline constexpr char ed25519_public_key[] = R"KMXT(${config.publicKey})KMXT";\n}\n`;
  return { config, cppHeader };
}

export class ApplicationService {
  constructor(store, rootSecret, config) {
    this.store = store;
    this.rootSecret = rootSecret;
    this.config = config;
  }

  async create(actor, merchantId, input) {
    assertRole(actor, [Roles.PLATFORM_ADMIN, Roles.MERCHANT_ADMIN]);
    assertMerchantAccess(actor, merchantId);
    const code = requireString(input.code, 'code', {
      min: 2,
      max: 32,
      pattern: APP_CODE_PATTERN,
    }).toUpperCase();
    const name = requireString(input.name, 'name', { min: 2, max: 100 });
    const description = optionalString(input.description, 'description', { min: 1, max: 500 });
    const settings = readSettings(input.settings || {}, {
      heartbeatSeconds: this.config.heartbeatSeconds,
    });
    const appId = randomUUID();
    const keyPair = generateSigningKeyPair();
    const signingKeyId = createHash('sha256').update(keyPair.publicKey).digest('hex').slice(0, 16);
    const encryptedPrivateKey = encryptText(this.rootSecret, `app-signing:${appId}`, keyPair.privateKey);
    // WS4 防重打包：注册应用时可选登记 Android 绑定约束（包名 / 签名证书指纹 / 最低版本）。
    // 未提供则字段缺省，verify/activate 时跳过完整性校验，保持向后兼容。花落/MIT。
    const binding = normalizeApplicationBinding(input);
    // 花落 / MIT：登记“当前最新版本”，供客户端显示该升到哪个版本。硬拒绝仍由
    // minVersionCode 决定；此处只描述最新版，不含下载地址。
    const release = normalizeClientRelease(input);
    const minVersionCode = binding.minVersionCode ?? null;
    const latestVersionCode = release.latestVersionCode ?? null;
    assertVersionPolicyConsistent(minVersionCode, latestVersionCode);
    const now = new Date().toISOString();
    const application = {
      id: appId,
      merchantId,
      code,
      name,
      description,
      status: 'active',
      settings,
      androidPackage: binding.androidPackage ?? null,
      signingCertificates: binding.signingCertificates ?? null,
      minVersionCode,
      latestVersionCode,
      latestVersionName: release.latestVersionName ?? null,
      releaseNotes: release.releaseNotes ?? null,
      signingKeyId,
      signingPublicKey: keyPair.publicKey,
      signingPrivateKeyEncrypted: encryptedPrivateKey,
      createdAt: now,
      updatedAt: now,
    };

    if (this.store.repositories?.applications) {
      return presentApplication(await this.store.repositories.applications.create(actor, application));
    }

    return this.store.transaction((state) => {
      findMerchantOrThrow(state, merchantId, { requireActive: true });
      if (state.applications.some((app) => app.merchantId === merchantId && app.code === code)) {
        throw new AppError('APPLICATION_CODE_EXISTS', 'Application code already exists for this merchant', 409);
      }
      state.applications.push(application);
      AuditService.append(state, {
        actor,
        merchantId,
        action: 'application.create',
        resourceType: 'application',
        resourceId: application.id,
        metadata: { code },
      });
      return presentApplication(application);
    });
  }

  async list(actor, merchantId) {
    assertMerchantAccess(actor, merchantId);
    if (this.store.repositories?.applications) {
      return (await this.store.repositories.applications.list(actor, merchantId)).map(presentApplication);
    }
    return this.store.read((state) => {
      findMerchantOrThrow(state, merchantId);
      return state.applications
        .filter((application) => application.merchantId === merchantId)
        .map(presentApplication);
    });
  }

  async get(actor, appId) {
    if (this.store.repositories?.applications) {
      return presentApplication(await this.store.repositories.applications.get(actor, appId));
    }
    return this.store.read((state) => {
      const application = findApplicationOrThrow(state, appId);
      assertMerchantAccess(actor, application.merchantId);
      return presentApplication(application);
    });
  }

  async setStatus(actor, appId, status) {
    assertRole(actor, [Roles.PLATFORM_ADMIN, Roles.MERCHANT_ADMIN]);
    const nextStatus = requireEnum(status, 'status', ['active', 'disabled']);
    if (this.store.repositories?.applications) {
      return presentApplication(await this.store.repositories.applications.setStatus(actor, appId, nextStatus));
    }
    return this.store.transaction((state) => {
      const application = findApplicationOrThrow(state, appId);
      assertMerchantAccess(actor, application.merchantId);
      findMerchantOrThrow(state, application.merchantId, { requireActive: true });
      application.status = nextStatus;
      application.updatedAt = new Date().toISOString();
      if (nextStatus === 'disabled') {
        state.clientSessions = state.clientSessions.filter((session) => session.appId !== appId);
      }
      AuditService.append(state, {
        actor,
        merchantId: application.merchantId,
        action: 'application.status.update',
        resourceType: 'application',
        resourceId: appId,
        metadata: { status: nextStatus },
      });
      return presentApplication(application);
    });
  }


  async update(actor, appId, input) {
    assertRole(actor, [Roles.PLATFORM_ADMIN, Roles.MERCHANT_ADMIN]);
    if (this.store.repositories?.applications) {
      const application = await this.store.repositories.applications.update(actor, appId, (current) => {
        if (input.name !== undefined) current.name = requireString(input.name, 'name', { min: 2, max: 100 });
        if (input.description !== undefined) current.description = optionalString(input.description, 'description', { min: 1, max: 500 });
        const settingInput = input.settings || input;
        current.settings = readSettings(settingInput, current.settings);
        applyBindingAndRelease(current, input);
      });
      return presentApplication(application);
    }
    return this.store.transaction((state) => {
      const application = findApplicationOrThrow(state, appId);
      assertMerchantAccess(actor, application.merchantId);
      findMerchantOrThrow(state, application.merchantId, { requireActive: true });
      if (input.name !== undefined) application.name = requireString(input.name, 'name', { min: 2, max: 100 });
      if (input.description !== undefined) application.description = optionalString(input.description, 'description', { min: 1, max: 500 });
      const settingInput = input.settings || input;
      application.settings = readSettings(settingInput, application.settings);
      applyBindingAndRelease(application, input);
      application.updatedAt = new Date().toISOString();
      AuditService.append(state, {
        actor,
        merchantId: application.merchantId,
        action: 'application.update',
        resourceType: 'application',
        resourceId: appId,
      });
      return presentApplication(application);
    });
  }

  async getPublicConfig(appId) {
    if (this.store.repositories?.applications) {
      const application = await this.store.repositories.applications.getActive(appId);
      return {
        appId: application.id,
        code: application.code,
        name: application.name,
        heartbeatSeconds: application.settings.heartbeatSeconds,
        offlineGraceSeconds: application.settings.offlineGraceSeconds,
        signing: {
          algorithm: 'Ed25519',
          keyId: application.signingKeyId,
          publicKey: application.signingPublicKey,
        },
      };
    }
    return this.store.read((state) => {
      const application = findApplicationOrThrow(state, appId, { requireActive: true });
      findMerchantOrThrow(state, application.merchantId, { requireActive: true });
      return {
        appId: application.id,
        code: application.code,
        name: application.name,
        heartbeatSeconds: application.settings.heartbeatSeconds,
        offlineGraceSeconds: application.settings.offlineGraceSeconds,
        signing: {
          algorithm: 'Ed25519',
          keyId: application.signingKeyId,
          publicKey: application.signingPublicKey,
        },
      };
    });
  }

  async getClientConfig(actor, appId) {
    if (this.store.repositories?.applications) {
      return createClientConfig(await this.store.repositories.applications.get(actor, appId), this.config);
    }
    return this.store.read((state) => {
      const application = findApplicationOrThrow(state, appId);
      assertMerchantAccess(actor, application.merchantId);
      const config = {
        protocolVersion: this.config.protocolVersion,
        baseUrl: this.config.publicBaseUrl,
        appId: application.id,
        keyId: application.signingKeyId,
        publicKey: application.signingPublicKey,
      };
      const cppHeader = `#pragma once\n// Generated by KMXT. Author: 花落. MIT License.\nnamespace kmxt::config {\ninline constexpr int protocol_version = ${config.protocolVersion};\ninline constexpr char base_url[] = R\"KMXT(${config.baseUrl})KMXT\";\ninline constexpr char app_id[] = R\"KMXT(${config.appId})KMXT\";\ninline constexpr char key_id[] = R\"KMXT(${config.keyId})KMXT\";\ninline constexpr char ed25519_public_key[] = R\"KMXT(${config.publicKey})KMXT\";\n}\n`;
      return { config, cppHeader };
    });
  }
}
